// Cadenas de interfaz compartidas (nav, footer, CTAs, formulario) — ca / es
const UI = {
  ca: {
    htmlLang: 'ca',
    skipToContent: 'Vés al contingut',
    nav: {
      home: 'Inici',
      services: 'Serveis',
      zona: 'Zona de servei',
      opinions: 'Opinions',
      faq: 'Preguntes freqüents',
      contact: 'Contacte',
    },
    cta: {
      call: 'Truca ara',
      whatsapp: 'Escriu per WhatsApp',
      quote: 'Demana pressupost',
      callShort: 'Trucar',
      waShort: 'WhatsApp',
      seeAllReviews: 'Veure totes les opinions a Google',
      viewService: 'Veure el servei',
      sendForm: 'Enviar i obrir WhatsApp',
    },
    trustStrip: {
      rating: `${'4,8'}★ · 157 opinions de Google`,
      since: 'Des de 1988',
      founders: 'Félix Galeano i Ramón Linares',
      area: 'Mataró i el Maresme',
    },
    footer: {
      hoursTitle: 'Horari',
      hours: ['Dilluns a divendres: 7:30–21:00', 'Dissabte: 7:30–14:00', 'Diumenge: tancat (urgències a consultar per WhatsApp)'],
      addressTitle: 'Taller',
      contactTitle: 'Contacte',
      legalTitle: 'Legal',
      legalLinks: {
        avisLegal: 'Avís legal',
        privacitat: 'Política de privacitat',
        cookies: 'Política de cookies',
      },
      langSwitch: 'Castellano',
      rights: 'Tots els drets reservats.',
      madeWith: 'Lampistes a Mataró des de 1988.',
    },
    form: {
      name: 'El teu nom',
      phone: 'Telèfon',
      message: 'Què et passa?',
      messagePlaceholder: 'Per exemple: tinc una fuita sota el fregaplats…',
      privacy: 'En enviar, acceptes la',
      privacyLink: 'política de privacitat',
      submit: 'Enviar i obrir WhatsApp',
    },
    langLabel: 'ca',
    otherLang: { code: 'es', label: 'Castellano' },
  },
  es: {
    htmlLang: 'es',
    skipToContent: 'Ir al contenido',
    nav: {
      home: 'Inicio',
      services: 'Servicios',
      zona: 'Zona de servicio',
      opinions: 'Opiniones',
      faq: 'Preguntas frecuentes',
      contact: 'Contacto',
    },
    cta: {
      call: 'Llamar ahora',
      whatsapp: 'Escribir por WhatsApp',
      quote: 'Pide presupuesto',
      callShort: 'Llamar',
      waShort: 'WhatsApp',
      seeAllReviews: 'Ver todas las reseñas en Google',
      viewService: 'Ver el servicio',
      sendForm: 'Enviar y abrir WhatsApp',
    },
    trustStrip: {
      rating: '4,8★ · 157 reseñas de Google',
      since: 'Desde 1988',
      founders: 'Félix Galeano y Ramón Linares',
      area: 'Mataró y el Maresme',
    },
    footer: {
      hoursTitle: 'Horario',
      hours: ['Lunes a viernes: 7:30–21:00', 'Sábado: 7:30–14:00', 'Domingo: cerrado (urgencias a consultar por WhatsApp)'],
      addressTitle: 'Taller',
      contactTitle: 'Contacto',
      legalTitle: 'Legal',
      legalLinks: {
        avisLegal: 'Aviso legal',
        privacitat: 'Política de privacidad',
        cookies: 'Política de cookies',
      },
      langSwitch: 'Català',
      rights: 'Todos los derechos reservados.',
      madeWith: 'Lampistas en Mataró desde 1988.',
    },
    form: {
      name: 'Tu nombre',
      phone: 'Teléfono',
      message: '¿Qué te pasa?',
      messagePlaceholder: 'Por ejemplo: tengo una fuga bajo el fregadero…',
      privacy: 'Al enviar, aceptas la',
      privacyLink: 'política de privacidad',
      submit: 'Enviar y abrir WhatsApp',
    },
    langLabel: 'es',
    otherLang: { code: 'ca', label: 'Català' },
  },
};

module.exports = { UI };
